accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import views

app_name= 'accounts'

urlpatterns =[
    path('login/',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    
    path('logout/',auth_views.LogoutView.as_view(),
    name='logout'),

    path('signup/',views.SignUp.as_view(),name='signup'),
    
]

posts/urls.py
from django.urls import path
from posts import views


app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include

from simplesocial import views

urlpatterns = [
    path('',views.HomePageView.as_view(),name='home'),
    
    path('admin/', admin.site.urls),
    
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),

    path('about/',views.AboutPage.as_view(),name='about'),
    path('feature/',views.FeaturePage.as_view(),name='feature'),
    path('developer/',views.DeveloperPage.as_view(),name='developer'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Infoverse </title>

<!-- bootstrap -->

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Alternative to Bootstrap 3 Glyphicons-->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> 


<!-- Google fonts -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">

<!-- CSS -->
<!-- <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}"> -->
<link rel="stylesheet" href="{% static 'simplesocial/css/check.css' %}">

<!-- Medium Editor -->

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<!-- <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8"> -->
<!-- <link rel="stylesheet" href="{% static 'simplesocial/css/check.css' %}"> -->




</head>
<body>
    
    
    <nav class="navbar navbar-inverse navbar-fixed-top mynav" role="navigation" id='navbar'>
      
        <div class="container" >

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand mynav " style='color: rgba(236, 214, 14, 0.657);' href="{% url 'home' %}">Infoverse</a>
              </div>
                
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                
                <ul class="nav navbar-nav mynav navbar-right">
                  
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style='color: red'> More <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'about' %}">About Site</a></li>
                        <li><a href="{% url 'feature' %}">Features</a></li>
                
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'developer' %}">Developer</a></li>

                        
                      </ul>
                    </li>
                  </ul>

                <ul class="nav navbar-nav mynav navbar-right" >

                    {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}">Post</a></li>
                    <li><a href="{% url 'groups:all' %}">Groups </a></li>
                    <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

                    {% endif %}

                </ul >

                

            </div>
        </div >
    </nav >
    <br></br>
    <br></br>
        
        <div class="container mycontent" >
            {% block content %}



            {% endblock %}
        </div >
    

</body>


<!-- <canvas id="canvas" ></canvas> -->
<script type="text/javascript" src="{% static 'simplesocial/js/check.js' %}"></script>
<!-- <script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"></script> -->

<!-- Need to have JQuery and Javascript for DropDown Actions to work -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <center><h1 style='color: rgba(236, 214, 14, 0.657);'> Welcome to Infoverse  </h1></center>

{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>You are now logged in</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>Thank you for visiting, Come Back Soon !!! </h1>
{% endblock %}